on: 
  push:
    branches:
      - master

name: Release

jobs:
  publish:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js v24
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Check if version has been updated 
        id: check
        uses: EndBug/version-check@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          diff-search: true

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Push to release branch
        if: steps.check.outputs.changed == 'true'
        run: |
          awk '!/^dist$/' .gitignore > tmp && mv tmp .gitignore
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "release"

      - name: Creating version tag
        if: steps.check.outputs.changed == 'true'
        run: |
          VERSION=${{ steps.check.outputs.version }}
          MAJOR=$(echo $VERSION | cut -d. -f1)
          git tag -fa v${VERSION} -m v${VERSION}
          git tag -fa v${MAJOR} -m v${VERSION}

      - name: Push changes
        if: steps.check.outputs.changed == 'true'
        run: git push origin HEAD:release --force --tags

      - name: Create Release
        if: steps.check.outputs.changed == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release create v${{ steps.check.outputs.version }} --title "Release v${{ steps.check.outputs.version }}" --notes ""

      - name: Delete release branch
        if: always() && steps.check.outputs.changed == 'true'
        run: git push origin --delete release || true
    